import {
  to = segment_function.id-ifnd_68cb9206618bf51219f4334f
  id = "ifnd_68cb9206618bf51219f4334f"
}

resource "segment_function" "id-ifnd_68cb9206618bf51219f4334f" {
  code          = "// This is the function that fetches traits from your Engage space.\nasync function fetchTraits(userId, settings) {\n\tconst spaceId = settings.spaceId;\n\tconst apiKey = settings.apiKey;\n\tconst base64Token = Buffer.from(`$${apiKey}:`).toString('base64');\n\n\tconst ttl = 10 * 60 * 1000; // 10 minutes TTL\n\n\treturn cache.load(`traits_$${userId}`, ttl, async () => {\n\t\ttry {\n\t\t\tconst response = await fetch(\n\t\t\t\t`https://profiles.segment.com/v1/spaces/$${spaceId}/collections/users/profiles/user_id:$${userId}/traits?limit=100`,\n\t\t\t\t{\n\t\t\t\t\theaders: {\n\t\t\t\t\t\tAuthorization: `Basic $${base64Token}`,\n\t\t\t\t\t\t'Content-Type': 'application/json'\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t);\n\n\t\t\tif (!response.ok) {\n\t\t\t\tthrow new Error(`Failed to fetch traits: HTTP $${response.status}`);\n\t\t\t}\n\n\t\t\tconst data = await response.json();\n\t\t\treturn data.traits || {};\n\t\t} catch (error) {\n\t\t\tconsole.error(`Error fetching traits for user $${userId}:`, error);\n\t\t\treturn {};\n\t\t}\n\t});\n}\n\n/**\n * Handle track event\n * @param  {SegmentTrackEvent} event\n * @param  {FunctionSettings} settings\n */\nasync function onTrack(event, settings) {\n\t{\n\t\tevent.event = `$${event.event}_notICP`;\n\t}\n\tconsole.log(event);\n\treturn event;\n}\n\n/**\n * Handle identify event\n * @param  {SegmentIdentifyEvent} event\n * @param  {FunctionSettings} settings\n */\nasync function onIdentify(event, settings) {\n\treturn event;\n}\n\n/**\n * Handle group event\n * @param  {SegmentGroupEvent} event\n * @param  {FunctionSettings} settings\n */\nasync function onGroup(event, settings) {\n\t// Learn more at https://segment.com/docs/connections/spec/group/\n\tthrow new EventNotSupported('group is not supported');\n}\n\n/**\n * Handle page event\n * @param  {SegmentPageEvent} event\n * @param  {FunctionSettings} settings\n */\nasync function onPage(event, settings) {\n\t// Learn more at https://segment.com/docs/connections/spec/page/\n\treturn event;\n}\n\n/**\n * Handle screen event\n * @param  {SegmentScreenEvent} event\n * @param  {FunctionSettings} settings\n */\nasync function onScreen(event, settings) {\n\t// Learn more at https://segment.com/docs/connections/spec/screen/\n\tthrow new EventNotSupported('screen is not supported');\n}\n\n/**\n * Handle alias event\n * @param  {SegmentAliasEvent} event\n * @param  {FunctionSettings} settings\n */\nasync function onAlias(event, settings) {\n\t// Learn more at https://segment.com/docs/connections/spec/alias/\n\tthrow new EventNotSupported('alias is not supported');\n}\n\n/**\n * Handle delete event\n * @param  {SegmentDeleteEvent} event\n * @param  {FunctionSettings} settings\n */\nasync function onDelete(event, settings) {\n\t// Learn more at https://segment.com/docs/partners/spec/#delete\n\tthrow new EventNotSupported('delete is not supported');\n}\n"
  description   = null
  display_name  = null
  logo_url      = "https://cdn.filepicker.io/api/file/RmPmpcBTQZKaFeGQrdG5"
  resource_type = "INSERT_DESTINATION"
  settings = [
  ]
}